;//Map header file for CHM project
;//Automatically generated by Easy CHM.
;//Website : http://www.zipghost.com
;//Email   : webmaster@zipghost.com
;//Date    : 2017/9/11 14:17:34

;//NOTE:
;//All strings after the ";" are commnets, they will be ignored by the CHM Compiler.

#define IDH_1003	1003	; 首页.html 首页.html
#define IDH_1001	1001	; 第二页.html 第二页.html
#define IDH_1000	1000	; 第三页.html 第三页.html
#define IDH_1002	1002	; 第四页.html 第四页.html
